Repository HIPReader/HIPReader, pull requests merged in 2025-04, with the labels that each got.

#13 Feat: books CRUD 기능 구현
  src/main/java/com/example/hipreader/common/dto/response/PageResponseDto.java
  src/main/java/com/example/hipreader/common/entity/TimeStamped.java
  src/main/java/com/example/hipreader/domain/book/controller/BooksController.java
  src/main/java/com/example/hipreader/domain/book/dto/request/BooksRequestDto.java
  src/main/java/com/example/hipreader/domain/book/dto/response/BooksResponseDto.java
  src/main/java/com/example/hipreader/domain/book/entity/Book.java
  src/main/java/com/example/hipreader/domain/book/entity/Books.java
  src/main/java/com/example/hipreader/domain/book/genre/Genre.java
  src/main/java/com/example/hipreader/domain/book/repository/BookRepository.java
  src/main/java/com/example/hipreader/domain/book/repository/BooksRepository.java
  src/main/java/com/example/hipreader/domain/book/service/BooksService.java
Labels: enhancement

#16 Fix/books
  src/main/java/com/example/hipreader/domain/book/dto/response/BooksResponseDto.java
  src/main/java/com/example/hipreader/domain/book/entity/Book.java
  src/main/java/com/example/hipreader/domain/book/repository/BookRepository.java
  src/main/java/com/example/hipreader/domain/book/repository/BooksRepository.java
  src/main/java/com/example/hipreader/domain/book/service/BooksService.java
Labels: wontfix

#19 feat : 인증인가 기능 구현
  build.gradle
  src/main/java/com/example/hipreader/HipreaderApplication.java
  src/main/java/com/example/hipreader/auth/controller/AuthController.java
  src/main/java/com/example/hipreader/auth/dto/request/RefreshTokenRequestDto.java
  src/main/java/com/example/hipreader/auth/dto/request/SignupRequestDto.java
  src/main/java/com/example/hipreader/auth/dto/response/SigninResponseDto.java
  src/main/java/com/example/hipreader/auth/dto/response/SignupResponseDto.java
  src/main/java/com/example/hipreader/auth/service/AuthService.java
  src/main/java/com/example/hipreader/common/config/SecurityConfig.java
  src/main/java/com/example/hipreader/common/exception/ErrorCode.java
  src/main/java/com/example/hipreader/common/util/JwtAuthenticationFilter.java
  src/main/java/com/example/hipreader/common/util/JwtAuthenticationToken.java
  src/main/java/com/example/hipreader/common/util/JwtUtil.java
  src/main/java/com/example/hipreader/domain/refreshtoken/entity/RefreshToken.java
  src/main/java/com/example/hipreader/domain/refreshtoken/repository/RefreshTokenRepository.java
  src/main/java/com/example/hipreader/domain/refreshtoken/service/RefreshTokenService.java
  src/main/java/com/example/hipreader/domain/user/entity/User.java
  src/main/java/com/example/hipreader/domain/user/role/UserRole.java
  src/test/java/com/example/hipreader/auth/service/AuthServiceTest.java
  src/test/java/com/example/hipreader/domain/user/service/UserServiceTest.java
Labels: enhancement

#21 feat: S3 이미지 업로드 기능 구현 #20
  build.gradle
  src/main/java/com/example/hipreader/common/config/S3Config.java
  src/main/java/com/example/hipreader/common/s3/controller/S3Controller.java
  src/main/java/com/example/hipreader/common/s3/dto/MultipleUploadResponseDto.java
  src/main/java/com/example/hipreader/common/s3/dto/UploadResponseDto.java
  src/main/java/com/example/hipreader/common/s3/service/S3Service.java
Labels: enhancement

#25 feat: book recommendation
  build.gradle
  src/main/java/com/example/hipreader/common/config/QueryDslConfig.java
  src/main/java/com/example/hipreader/domain/book/controller/BookRecommendController.java
  src/main/java/com/example/hipreader/domain/book/dto/response/BookRecommendResponseDto.java
  src/main/java/com/example/hipreader/domain/book/service/BookRecommendService.java
  src/main/java/com/example/hipreader/domain/user/age/AgeGroup.java
  src/main/java/com/example/hipreader/domain/userbook/repository/UserBookRepository.java
  src/main/java/com/example/hipreader/domain/userbook/repository/UserBookRepositoryCustom.java
  src/main/java/com/example/hipreader/domain/userbook/repository/UserBookRepositoryImpl.java
Labels: enhancement

#28 feat: 책 추천 Redis 캐싱 도입
  src/main/java/com/example/hipreader/common/config/RedisConfig.java
  src/main/java/com/example/hipreader/common/config/SecurityConfig.java
  src/main/java/com/example/hipreader/common/dto/response/PageResponseDto.java
  src/main/java/com/example/hipreader/domain/book/controller/BookRecommendController.java
  src/main/java/com/example/hipreader/domain/book/dto/response/BookRecommendResponseDto.java
  src/main/java/com/example/hipreader/domain/book/service/BookRecommendService.java
Labels: enhancement

#46 feat/userdiscussion : 토론방 입장 신청, 수락, 거절 기능구현
  src/main/java/com/example/hipreader/common/exception/ErrorCode.java
  src/main/java/com/example/hipreader/domain/userdiscussion/ApplicationStatus/ApplicationStatus.java
  src/main/java/com/example/hipreader/domain/userdiscussion/controller/UserDiscussionController.java
  src/main/java/com/example/hipreader/domain/userdiscussion/dto/request/ApplyUserDiscussionRequestDto.java
  src/main/java/com/example/hipreader/domain/userdiscussion/dto/response/ApplyUserDiscussionResponseDto.java
  src/main/java/com/example/hipreader/domain/userdiscussion/dto/response/ApproveUserDiscussionResponseDto.java
  src/main/java/com/example/hipreader/domain/userdiscussion/dto/response/RejectUserDiscussionResponseDto.java
  src/main/java/com/example/hipreader/domain/userdiscussion/entity/UserDiscussion.java
  src/main/java/com/example/hipreader/domain/userdiscussion/repository/UserDiscussionRepository.java
  src/main/java/com/example/hipreader/domain/userdiscussion/service/UserDiscussionService.java
  src/main/java/com/example/hipreader/domain/userdiscussion/service/UserDiscussionServiceImpl.java
Labels: enhancement

#47 feat: 책 추천 기능에 Elasticsearch 도입 및 마이그레이션 구현
  build.gradle
  src/main/java/com/example/hipreader/common/config/ElasticsearchConfig.java
  src/main/java/com/example/hipreader/common/config/SecurityConfig.java
  src/main/java/com/example/hipreader/common/config/StartupMigrationRunner.java
  src/main/java/com/example/hipreader/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/hipreader/domain/book/controller/BookRecommendController.java
  src/main/java/com/example/hipreader/domain/book/dto/response/BookRecommendResponseDto.java
  src/main/java/com/example/hipreader/domain/book/service/BookRecommendService.java
  src/main/java/com/example/hipreader/domain/userbook/document/UserBookDocument.java
  src/main/java/com/example/hipreader/domain/userbook/repository/UserBookRepository.java
  src/main/java/com/example/hipreader/domain/userbook/repository/UserBookRepositoryCustom.java
  src/main/java/com/example/hipreader/domain/userbook/repository/UserBookRepositoryImpl.java
  src/main/java/com/example/hipreader/domain/userbook/service/UserBookDocumentMigrationService.java
  src/main/java/com/example/hipreader/domain/userbook/service/UserBookSearchService.java
Labels: enhancement

#49 feat/userdiscussion : 기능 고도화 , 토론방 참가 신청, 승인, 거절 시 Gmail 알림 받는 기능 구현.
  build.gradle
  src/main/java/com/example/hipreader/common/config/RabbitConfig.java
  src/main/java/com/example/hipreader/domain/userdiscussion/consumer/NotificationConsumer.java
  src/main/java/com/example/hipreader/domain/userdiscussion/dto/response/NotificationMessage.java
  src/main/java/com/example/hipreader/domain/userdiscussion/producer/NotificationProducer.java
  src/main/java/com/example/hipreader/domain/userdiscussion/service/EmailService.java
  src/main/java/com/example/hipreader/domain/userdiscussion/service/NotificationService.java
  src/main/java/com/example/hipreader/domain/userdiscussion/service/UserDiscussionServiceImpl.java
  src/main/resources/templates/email-template.html
Labels: enhancement

#57 feat/swagger : swagger 기능 구현
  build.gradle
  src/main/java/com/example/hipreader/common/config/SecurityConfig.java
  src/main/java/com/example/hipreader/common/config/SwaggerConfig.java
  src/main/java/com/example/hipreader/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/hipreader/domain/bookscore/batch/BookScoreInitializer.java
  src/main/java/com/example/hipreader/domain/bookscore/entity/BookScore.java
  src/main/java/com/example/hipreader/domain/discussion/entity/Discussion.java
  src/test/java/com/example/hipreader/domain/bookscore/service/BookScoreServiceTest.java
Labels: enhancement

#58 feat: Kibana를 활용한 Elasticsearch 시각화 테스트 환경 구성
  src/main/java/com/example/hipreader/common/config/ElasticsearchConfig.java
  src/main/java/com/example/hipreader/domain/userbook/document/UserBookDocument.java
  src/main/java/com/example/hipreader/domain/userbook/repository/UserBookRepository.java
  src/main/java/com/example/hipreader/domain/userbook/service/UserBookDocumentMigrationService.java
Labels: enhancement

#71 feat: 토론방 채팅 WebSocket 으로 구현
  build.gradle
  src/main/java/com/example/hipreader/auth/dto/response/SigninResponseDto.java
  src/main/java/com/example/hipreader/auth/service/AuthService.java
  src/main/java/com/example/hipreader/common/config/SecurityConfig.java
  src/main/java/com/example/hipreader/common/config/WebConfig.java
  src/main/java/com/example/hipreader/common/config/WebSocketConfig.java
  src/main/java/com/example/hipreader/common/exception/ErrorCode.java
  src/main/java/com/example/hipreader/common/util/JwtUtil.java
  src/main/java/com/example/hipreader/domain/chatmessage/controller/ChatMessageController.java
  src/main/java/com/example/hipreader/domain/chatmessage/controller/ChatRoomController.java
  src/main/java/com/example/hipreader/domain/chatmessage/dto/request/ChatMessageRequestDto.java
  src/main/java/com/example/hipreader/domain/chatmessage/dto/response/GetChatMessageResponseDto.java
  src/main/java/com/example/hipreader/domain/chatmessage/entity/ChatMessage.java
  src/main/java/com/example/hipreader/domain/chatmessage/repository/ChatMessageRepository.java
  src/main/java/com/example/hipreader/domain/chatmessage/service/ChatMessageService.java
  src/main/java/com/example/hipreader/domain/chatmessage/websocket/ChatHandshakeInterceptor.java
  src/main/java/com/example/hipreader/domain/chatmessage/websocket/ChatWebSocketHandler.java
  src/main/java/com/example/hipreader/domain/user/repository/UserRepository.java
  src/main/java/com/example/hipreader/domain/userdiscussion/repository/UserDiscussionRepository.java
  src/main/resources/chat-test.http
  src/main/resources/static/chat.html
  src/main/resources/static/login.html
Labels: enhancement

#83 fix:auth 비밀번호 찾기 기능구현, 403 Forbidden 외 잘못된 오류코드 출력 이슈 해결
  src/main/java/com/example/hipreader/auth/controller/AuthController.java
  src/main/java/com/example/hipreader/auth/dto/request/ForgotPasswordRequestDto.java
  src/main/java/com/example/hipreader/auth/dto/request/ResetPasswordRequestDto.java
  src/main/java/com/example/hipreader/auth/entity/PasswordResetToken.java
  src/main/java/com/example/hipreader/auth/repository/PasswordResetTokenRepository.java
  src/main/java/com/example/hipreader/auth/service/AuthService.java
  src/main/java/com/example/hipreader/common/config/SecurityConfig.java
  src/main/java/com/example/hipreader/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/hipreader/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/hipreader/domain/user/entity/User.java
  src/main/java/com/example/hipreader/domain/userdiscussion/service/EmailService.java
  src/main/resources/templates/email/password-reset.html
Labels: bug
